### ISSUE TITLE
Installing Python Depndencies for ROS Nodes in our Dockerized Environments

### ISSUE THREAD

**Issue by cerashdan** [Autobots-Visman/reinforcement-learning#4]
Was about to install PyTorch to continue with the image embeddings, and was not sure what is the best way forward to install python dependency for a ROS node in our environment? 

Should we install it using the dockerfile using package manager? 
or include it somehow in the catkin build process? if yes, I'm not clear how to do that

**Comment by acmiyaguchi** [comment]
https://github.com/Autobots-Visman/reinforcement-learning/blob/a2758091957b5daf9e6b6837f56f6de75ba1f0ca/docker/Dockerfile#L112-L116

Install stuff to poetry: 

```bash
poetry install
poetry add pytorch
poetry lock
```

https://github.com/Autobots-Visman/reinforcement-learning/blob/a2758091957b5daf9e6b6837f56f6de75ba1f0ca/pyproject.toml#L9-L14

This automatically gets installed to the environment. We refactor the project a bit and have a separate package for the agent and create a new poetry config for the ros directory, but this should suffice for now.
