### ISSUE TITLE
Using image_publisher to unit_test img2vec 

### ISSUE THREAD

**Issue by cerashdan** [Autobots-Visman/reinforcement-learning#5]
Hello, 

I'm working on img2vec and was thinking what could be the best way to unit test the node. From what I know: 

Image --> Img2Vec --> Image Embeddings 

To do that, we could use http://wiki.ros.org/image_publisher, and run the following command: 

rosrun image_publisher image_publisher /opt/ros/indigo/share/rviz/images/splash.png

A similar quesiton to the previous issue, what would be the best way to install the image_publisher package in our dockerized environment @acmiyaguchi ?

**Comment by acmiyaguchi** [comment]
If you want to install packages, add the dependencies to the package.xml and then run this command inside of a running container: https://github.com/Autobots-Visman/reinforcement-learning/blob/a2758091957b5daf9e6b6837f56f6de75ba1f0ca/docker/Dockerfile#L34-L41

I would structure unit tests like this: https://github.com/ivalab/GraspKpNet/blob/main/ros/gknet_perception/tests/test_detect.test You can use the image publisher package which seems fine (or just write you own static image publisher). But I would definitely use `ros_pytest` 100%.

**Comment by cerashdan** [comment]
Noted, added image_publisher as a <test_depend> in package.xml file in img2vec

Working file after running catkin make
